title: evsrt notepad
description: cybersecurity, windows, linux, blog
theme: just-the-docs
url: https://evsrt.com

# Color scheme supports "light" (default) and "dark"
color_scheme: light

search_enabled: true
nav_enabled: true
heading_anchors: true
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
